#!/bin/sh

brew install act
brew install automake
brew install aws/tap/copilot-cli
brew install awscli
brew install bat
brew install bpytop
brew install bufbuild/buf/buf
brew install cloudflared
brew install commitlint
brew install dart
brew install dnsmasq
brew install docker-buildx
brew install duf # df alternative
brew install dust # du alternative
brew install eksctl
brew install eslint
brew install exercism
brew install eza
brew install fd # find alternative
brew install ffmpeg
brew install fontforge
brew install fzf
brew install git
brew install git-credential-libsecret
brew install git-lfs
brew install gitlint
brew install gofumpt
brew install gojq
brew install golang-migrate
brew install goreleaser
brew install hashicorp/tap/terraform
brew install hashicorp/tap/terraform-ls
brew install helm
brew install httpie
brew install icdiff
brew install jq
brew install luarocks
brew install mas
brew install minikube
brew install mongodb/brew/mongodb-database-tools
brew install mongosh
brew install monika
brew install mycli
brew install neovim
brew install netlify-cli
brew install nexttrace
brew install openjdk@11
brew install php
brew install pre-commit
brew install protobuf
brew install pulumi/tap/pulumi
brew install rcm
brew install ripgrep
brew install sass/sass/sass
brew install shellcheck
brew install stripe/stripe-cli/stripe
brew install tcptraceroute
brew install tfsec
brew install the_silver_searcher
brew install tmux
brew install tree
brew install watch
brew install wget
brew install whois
brew install zlib
brew install zsh
brew install zsh-autosuggestions
brew install zsh-completions
brew install zsh-syntax-highlighting
